version: "3"
services:
  ampwars-backend:
    build: .
    environment:
      PGUSER: postgres
      PGPASSWORD:
      PGDATABASE: ampwars
      PGPORT: 5432
      PGHOST: postgres
      PGSSL: "false"
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: "postgres:12.1-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ampwars
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
